version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3002
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432" 
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cbt_simulador_plantas
    volumes:
      - pgdata_sim_plantas:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata_sim_plantas:
